Disimport unicode_literals from setup script
These imports seem to (a) serve no function and (b) spuriously break `distutils`. For example:

```
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_py.py", line 335, in build_module
        package)
    TypeError: u'dirtbike' must be a string (dot-separated), list, or tuple
```

It is not a `str` because `u'dirtbike'` is `unicode`. Lame but avoidable.